language: generic
sudo: required
dist: trusty
notifications:
  email: false
os: linux
matrix:
  include:
    - os: linux
      env:
        - SWIFT_VERSION=5.0.1
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swift package resolve
      script:
        - swift build
        - swift test
    - os: linux
      env:
        - SWIFT_VERSION=5.3.1
      install:
        - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
        - swift package resolve
      script:
        - swift build
        - swift test
    - os: osx
      osx_image: xcode10.2
      env:
        - SWIFT_VERSION=system
      install:
        - swift package resolve
      script:
        - xcodebuild -scheme Finite -enableCodeCoverage YES test | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - os: osx
      osx_image: xcode12.2
      env:
        - SWIFT_VERSION=system
      install:
        - swift package resolve
      script:
        - xcodebuild -scheme Finite -enableCodeCoverage YES test | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash)
