language: generic
sudo: required
dist: trusty
notifications:
  email: false
os: linux
env:
  matrix:
    - SWIFT_VERSION=5.0.1
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - SWIFT_VERSION=system
      script:
        - xcodebuild -scheme Finite -enableCodeCoverage YES test | xcpretty
      after_success:
        - bash <(curl -s https://codecov.io/bash)
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build
  - swift test
